### ISSUE TITLE
关于 ctrl 和 shift 配合 space 的问题

### ISSUE THREAD

**Issue by xntzmk** [plum9696/SpaceFn#1]
如果我先按住 ctrl / shift 再按住 space ，fn 功能就会失效。但是先按住space就正常使用spaceFn

**Comment by plum9696** [comment]
> 如果我先按住 ctrl / shift 再按住 space ，fn 功能就会失效。但是先按住space就正常使用spaceFn  

我已经修复到了[v1.0.2](https://github.com/plum9696/SpaceFn/commit/fe1546307f1021ced7fd00f63071efc9a14d510c)
[release](https://github.com/plum9696/SpaceFn/releases/tag/v1.0.1)

**Comment by plum9696** [comment]
> 如果我先按住 ctrl / shift 再按住 space ，fn 功能就会失效。但是先按住space就正常使用spaceFn
